[project]
name = "mint-loan"
authors = ["Loan Protocol Team"]
description = "A decentralized lending platform with flexible loan minting and governance"
telemetry = false
requirements = []
[contracts.loan-governance]
path = "contracts/loan-governance.clar"
depends_on = []

[contracts.loan-marketplace]
path = "contracts/loan-marketplace.clar"
depends_on = []

[contracts.borrower-reputation]
path = "contracts/borrower-reputation.clar"
depends_on = []

[contracts.loan-terms]
path = "contracts/loan-terms.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
